# Generated by Django 4.0 on 2021-12-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='photo_url_path',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
