# Generated by Django 4.0 on 2021-12-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique_shop', '0002_alter_categories_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='photo_url_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
